In [144]:
import pandas as pd
import numpy as np
MINTEMP = 26.0

# high range of the sensor (this will be red on the screen)
MAXTEMP = 32.0

# how many color values we can have
COLORDEPTH = 1024

In [155]:
#function to convert from pixel to C
def unmap_value(p, in_min, in_max, out_min, out_max):
    return (((p - out_min) * (in_max - in_min)) / (out_max - out_min)) + in_min

In [156]:
revert = unmap_value(2046, MINTEMP, MAXTEMP, 0, COLORDEPTH - 1)
print(revert)

38.0

In [145]:
path = "/Users/shrimathavan/Desktop/QuadrantInfo/bottomrightquadtry.csv"
path_ll = "/Users/shrimathavan/Desktop/QuadrantInfo/lowleftquad.csv"
path_tl = "/Users/shrimathavan/Desktop/QuadrantInfo/topleftquad.csv"
path_tr = "/Users/shrimathavan/Desktop/QuadrantInfo/toprightquad.csv"

In [146]:
df = pd.read_csv(path)
dfll = pd.read_csv(path_ll)
dftl = pd.read_csv(path_tl)
dftr = pd.read_csv(path_tr)

In [147]:
df.head(10)

,-682,-554.125,-596.75,-298.375,-213.125,-213.125.1,-298.375.1,-298.375.2,-596.75.1,-596.75.2,...,2301.75.1,1790.25,-596.75.6,-554.125.4,-127.875.1,639.375,2046,2301.75.2,1875.5,937.75.1
0,-682.000,-554.125,-596.750,-298.375,-213.125,-213.125,-298.375,-341.000,-596.750,-682.000,...,2301.750,1577.125,-596.750,-468.875,-383.625,554.125,2046.000,2088.625,1705.000,809.875
1,-639.375,-596.750,-724.625,-383.625,-213.125,-298.375,-383.625,-341.000,-596.750,-682.000,...,2259.125,1577.125,-468.875,-511.500,-255.750,682.000,1918.125,2344.375,1832.875,767.250
2,-596.750,-554.125,-554.125,-383.625,-213.125,-170.500,-341.000,-383.625,-639.375,-596.750,...,2259.125,1577.125,-468.875,-511.500,-255.750,682.000,1918.125,2344.375,1832.875,767.250
3,-639.375,-596.750,-639.375,-255.750,-127.875,-255.750,-426.250,-383.625,-639.375,-682.000,...,2344.375,1662.375,-596.750,-511.500,-383.625,724.625,2003.375,2301.750,1875.500,895.125
4,-639.375,-596.750,-639.375,-255.750,-127.875,-255.750,-426.250,-383.625,-639.375,-682.000,...,2344.375,1747.625,-554.125,-468.875,-255.750,809.875,2173.875,2259.125,1960.750,895.125
5,-554.125,-639.375,-639.375,-341.000,-213.125,-213.125,-383.625,-341.000,-596.750,-639.375,...,2344.375,1747.625,-554.125,-468.875,-255.750,852.500,2088.625,2301.750,1875.500,895.125
6,-596.750,-554.125,-596.750,-341.000,-213.125,-255.750,-341.000,-213.125,-682.000,-639.375,...,2387.000,1619.750,-554.125,-426.250,-255.750,852.500,2088.625,2301.750,1875.500,895.125
7,-682.000,-639.375,-596.750,-383.625,-170.500,-255.750,-341.000,-341.000,-639.375,-596.750,...,2259.125,1747.625,-639.375,-426.250,-298.375,809.875,2131.250,2259.125,1918.125,852.500
8,-682.000,-639.375,-596.750,-383.625,-170.500,-255.750,-341.000,-341.000,-639.375,-596.750,...,2344.375,1705.000,-511.500,-468.875,-170.500,852.500,2131.250,2216.500,1960.750,937.750
9,-596.750,-596.750,-511.500,-341.000,-213.125,-213.125,-255.750,-383.625,-682.000,-682.000,...,2344.375,1705.000,-511.500,-468.875,-170.500,852.500,2216.500,2344.375,1960.750,980.375

In [148]:
np_array = df.to_numpy()
npll = dfll.to_numpy()
nptl = dftl.to_numpy()
nptr = dftr.to_numpy()
print(np_array[2])

[-596.75  -554.125 -554.125 -383.625 -213.125 -170.5   -341.    -383.625
 -639.375 -596.75  -596.75  -426.25  -213.125 -127.875  -42.625 -170.5
 -468.875 -596.75  -554.125 -383.625 -213.125    0.     170.5    127.875
 -682.    -511.5   -426.25  -298.375  468.875 1150.875 1108.25   341.
 -554.125 -511.5   -298.375  639.375 2131.25  2429.625 2259.125 1449.25
 -596.75  -468.875 -255.75  1577.125 2514.875 2514.875 2429.625 1875.5
 -554.125 -468.875 -127.875 1619.75  2514.875 2429.625 2259.125 1577.125
 -468.875 -511.5   -255.75   682.    1918.125 2344.375 1832.875  767.25 ]

In [149]:
count_br = 0
bottomright_rs = []
for arr in np_array:
    bottomright_rs.append(np.reshape(np_array[count_br], (8, 8),order='F'))
    count_br+=1

#bottom right quadrant

In [151]:
print(bottomright_rs[26]) #F
#QUADRANT SPLIT FOR BOTTOM RIGHT
bot_right = [(bottomright_rs[26])[4][4:], (bottomright_rs[26])[5][4:],(bottomright_rs[26])[6][4:],(bottomright_rs[26])[7][4:]]
for arr in bot_right:
    print(arr)
    for pixel_row in arr:
#         print(pixel_row)
        revert = unmap_value(float(pixel_row), MINTEMP, MAXTEMP, 0, COLORDEPTH - 1)
        print(revert)
# print(bot_right)
print(unmap_value(-596.755,MINTEMP, MAXTEMP, 0, COLORDEPTH - 1))

[[-554.125 -596.75  -554.125 -639.375 -639.375 -426.25  -554.125 -639.375]
 [-554.125 -596.75  -554.125 -426.25  -554.125 -426.25  -468.875 -468.875]
 [-639.375 -596.75  -554.125 -383.625 -298.375 -298.375 -298.375 -298.375]
 [-468.875 -468.875 -426.25   -85.25   468.875 1278.75  1236.125  341.   ]
 [-127.875 -383.625 -213.125  596.75  2216.5   2514.875 2472.25  1918.125]
 [-127.875 -170.5     42.625 1491.875 2514.875 2514.875 2472.25  2216.5  ]
 [-341.     -85.25   383.625 1577.125 2472.25  2472.25  2387.    1875.5  ]
 [-213.125 -127.875  170.5    809.875 1960.75  2216.5   1960.75  1108.25 ]]
[2216.5   2514.875 2472.25  1918.125]
39.0
40.75
40.5
37.25
[2514.875 2514.875 2472.25  2216.5  ]
40.75
40.75
40.5
39.0
[2472.25 2472.25 2387.   1875.5 ]
40.5
40.5
40.0
37.0
[1960.75 2216.5  1960.75 1108.25]
37.5
39.0
37.5
32.5
22.499970674486804

In [131]:
print(bottomright_rs[106]) #checks out, it is bottom right C

[[-639.375 -596.75 -596.75 -511.5 -511.5 -596.75 -511.5 -639.375]
 [-596.75 -596.75 -468.875 -298.375 -255.75 -383.625 -511.5 -639.375]
 [-554.125 -511.5 -298.375 639.375 1193.5 468.875 -255.75 -554.125]
 [-213.125 -341.0 511.5 2173.875 2429.625 2173.875 170.5 -426.25]
 [-298.375 -170.5 1023.0 2344.375 2259.125 2173.875 511.5 -383.625]
 [-341.0 -85.25 426.25 1832.875 2088.625 1577.125 -85.25 -383.625]
 [-468.875 -170.5 42.625 341.0 596.75 85.25 -255.75 -468.875]
 [-426.25 -341.0 -127.875 -213.125 -42.625 -255.75 -341.0 ' -511.5]']]

In [132]:
count_ll = 0
lowerleft_rs = []
for arr in npll:
    lowerleft_rs.append(np.reshape(npll[count_ll], (8, 8),order='F'))
    count_ll+=1
#lower left quadrant

In [133]:
print(lowerleft_rs[26]) #Order F
#QUADRANT SPLIT FOR LOWER LEFT
bot_left = [(lowerleft_rs[26])[4][:4], (lowerleft_rs[26])[5][:4],(lowerleft_rs[26])[6][:4]]
for arr in bot_left:
    print(arr)

[['[-127.875' -170.5 -85.25 -170.5 -255.75 -255.75 -341.0 -682.0]
 [-170.5 -127.875 -85.25 0.0 -170.5 -341.0 -767.25 -767.25]
 [-85.25 -85.25 0.0 -127.875 -213.125 -554.125 -682.0 -852.5]
 [0.0 0.0 42.625 -170.5 -341.0 -596.75 -639.375 -809.875]
 [-255.75 383.625 426.25 -298.375 -511.5 -596.75 -724.625 -767.25]
 [-255.75 298.375 255.75 -255.75 -596.75 -682.0 -724.625 -596.75]
 [-468.875 -85.25 85.25 -426.25 -554.125 -596.75 -682.0 -682.0]
 [-426.25 -511.5 -426.25 -468.875 -511.5 -682.0 -554.125 ' -724.625]']]
[-255.75 383.625 426.25 -298.375]
[-255.75 298.375 255.75 -255.75]
[-468.875 -85.25 85.25 -426.25]

In [134]:
print(lowerleft_rs[26])#order C

[['[-127.875' -170.5 -85.25 -170.5 -255.75 -255.75 -341.0 -682.0]
 [-170.5 -127.875 -85.25 0.0 -170.5 -341.0 -767.25 -767.25]
 [-85.25 -85.25 0.0 -127.875 -213.125 -554.125 -682.0 -852.5]
 [0.0 0.0 42.625 -170.5 -341.0 -596.75 -639.375 -809.875]
 [-255.75 383.625 426.25 -298.375 -511.5 -596.75 -724.625 -767.25]
 [-255.75 298.375 255.75 -255.75 -596.75 -682.0 -724.625 -596.75]
 [-468.875 -85.25 85.25 -426.25 -554.125 -596.75 -682.0 -682.0]
 [-426.25 -511.5 -426.25 -468.875 -511.5 -682.0 -554.125 ' -724.625]']]

In [135]:
count_tl = 0
topleft_rs = []
for arr in nptl:
    topleft_rs.append(np.reshape(nptl[count_tl], (8, 8),order='F'))
    
    count_tl+=1

#top left quadrant

In [139]:
top_left = [(topleft_rs[33])[0][:4], (topleft_rs[33])[1][:4],(topleft_rs[33])[2][:4],(topleft_rs[33])[3][:4]]
#QUADRANT SPLIT FOR TOP LEFT
for arr in top_left:
    print(arr)
#     for pixel_row in arr:
#         pixel_row.strip("[")
#         print(pixel_row)
#         revert = unmap_value(float(pixel), MINTEMP, MAXTEMP, 0, COLORDEPTH - 1)
#         print(revert)
    
print(topleft_rs[33]) #F

['[213.125' 1364.0 2813.25 1832.875]
[468.875 2472.25 3026.375 2387.0]
[0.0 1364.0 2173.875 596.75]
[-341.0 -255.75 -298.375 -426.25]
[['[213.125' 1364.0 2813.25 1832.875 -255.75 -596.75 -596.75 -596.75]
 [468.875 2472.25 3026.375 2387.0 -298.375 -639.375 -639.375 -682.0]
 [0.0 1364.0 2173.875 596.75 -383.625 -596.75 -639.375 -682.0]
 [-341.0 -255.75 -298.375 -426.25 -511.5 -596.75 -596.75 -767.25]
 [-383.625 -511.5 -468.875 -596.75 -596.75 -724.625 -724.625 -767.25]
 [-383.625 -596.75 -511.5 -682.0 -682.0 -767.25 -682.0 -767.25]
 [-511.5 -596.75 -682.0 -639.375 -639.375 -596.75 -682.0 -767.25]
 [-639.375 -639.375 -554.125 -554.125 -554.125 -639.375 -682.0
  ' -724.625]']]

In [115]:
# rounded_down_integer_array = topleft_rs[30].astype(float)
print(topleft_rs[30]) #order C

[['[170.5' 1406.625 2770.625 1918.125 -213.125 -554.125 -468.875 -639.375]
 [426.25 2472.25 3026.375 2429.625 -213.125 -511.5 -682.0 -639.375]
 [85.25 1364.0 2088.625 682.0 -426.25 -639.375 -596.75 -639.375]
 [-341.0 -255.75 -255.75 -468.875 -596.75 -639.375 -682.0 -767.25]
 [-383.625 -554.125 -468.875 -596.75 -639.375 -724.625 -682.0 -809.875]
 [-383.625 -511.5 -511.5 -724.625 -639.375 -724.625 -767.25 -639.375]
 [-596.75 -554.125 -682.0 -596.75 -682.0 -596.75 -767.25 -639.375]
 [-724.625 -596.75 -639.375 -596.75 -596.75 -724.625 -682.0 ' -682.0]']]

In [53]:
count_tr = 0
topright_rs = []
for arr in nptr:
    topright_rs.append(np.reshape(nptr[count_tr], (8, 8),order='F'))
    count_tr+=1
#top right quadrant

In [54]:
print(topright_rs[30]) #order F

[['[-170.5' -426.25 -255.75 -42.625 1321.375 1960.75 1832.875 554.125]
 [-298.375 -468.875 -341.0 -42.625 1577.125 1577.125 980.375 -170.5]
 [-639.375 -511.5 -468.875 -298.375 980.375 1321.375 170.5 -298.375]
 [-724.625 -639.375 -511.5 -511.5 -298.375 -213.125 -341.0 -511.5]
 [-724.625 -724.625 -639.375 -639.375 -511.5 -511.5 -554.125 -596.75]
 [-767.25 -767.25 -639.375 -724.625 -596.75 -724.625 -639.375 -596.75]
 [-724.625 -724.625 -682.0 -639.375 -682.0 -596.75 -809.875 -639.375]
 [-767.25 -767.25 -724.625 -682.0 -682.0 -809.875 -682.0 ' -724.625]']]

In [52]:
print(topright_rs[30]) #Order C

[['[-170.5' -298.375 -639.375 -724.625 -724.625 -767.25 -724.625 -767.25]
 [-426.25 -468.875 -511.5 -639.375 -724.625 -767.25 -724.625 -767.25]
 [-255.75 -341.0 -468.875 -511.5 -639.375 -639.375 -682.0 -724.625]
 [-42.625 -42.625 -298.375 -511.5 -639.375 -724.625 -639.375 -682.0]
 [1321.375 1577.125 980.375 -298.375 -511.5 -596.75 -682.0 -682.0]
 [1960.75 1577.125 1321.375 -213.125 -511.5 -724.625 -596.75 -809.875]
 [1832.875 980.375 170.5 -341.0 -554.125 -639.375 -809.875 -682.0]
 [554.125 -170.5 -298.375 -511.5 -596.75 -596.75 -639.375 ' -724.625]']]